<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Template.Messaging.Worker-de8fee6f-0f4a-4bee-b472-37c229c24811</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.3.0"/>
        <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1"/>
        <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.0"/>
        <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1"/>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3"/>
        <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Template.Transaction\Template.Transaction.csproj"/>
    </ItemGroup>
</Project>
