// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Persistence.Context;

#nullable disable

namespace Template.Persistence.Context.Migrations
{
    [DbContext(typeof(DatabaseDbContext))]
    partial class DatabaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Template.Domain.Components.Customers.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("ApiKey", "Template.Domain.Components.Customers.Models.Customer.ApiKey#ApiKey", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("Expired")
                                .HasColumnType("bit")
                                .HasColumnName("ApiKeyExpired");

                            b1.Property<Guid>("Key")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ApiKey");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Information", "Template.Domain.Components.Customers.Models.Customer.Information#CustomerInformation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Subscription", "Template.Domain.Components.Customers.Models.Customer.Subscription#Subscription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("SubscriptionType");
                        });

                    b.HasKey("Id");

                    b.ToTable("Customer", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
