#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

RUN apk add icu-libs icu-data-full
RUN apk add tzdata

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build

WORKDIR /src
COPY ./*.sln ./

COPY ./src/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done

COPY ./tests/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p tests/${file%.*}/ && mv $file tests/${file%.*}/; done

RUN dotnet restore "Template.sln"
COPY . .
RUN dotnet build "Template.sln"  -c Release -o /app/build 
RUN dotnet test "Template.sln"  -c Release 


FROM build AS publish
RUN dotnet publish "./src/Template.Host/Template.Host.csproj" -c Release -o /app/publish /p:UseAppHost=false




FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Template.Host.dll"]