// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Persistence.Contexts.Template;

#nullable disable

namespace Template.Persistence.Contexts.Template.Migrations;

[DbContext(typeof(TemplateContext))]
partial class TemplateContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Template.Domain.Models.Template.TemplateAggregateRoot", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Template", (string)null);
            });

        modelBuilder.Entity("Template.Domain.Models.Template.TemplateAggregateRoot", b =>
            {
                b.OwnsOne("Template.Domain.Models.Template.TemplateDescription", "Description", b1 =>
                    {
                        b1.Property<int>("TemplateAggregateRootId")
                            .HasColumnType("int");

                        b1.Property<string>("Name")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.Property<string>("Version")
                            .IsRequired()
                            .HasColumnType("nvarchar(max)");

                        b1.HasKey("TemplateAggregateRootId");

                        b1.ToTable("TemplateDescription", (string)null);

                        b1.WithOwner()
                            .HasForeignKey("TemplateAggregateRootId");
                    });

                b.Navigation("Description")
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
